services:
  - type: web
    name: qenani-ledger
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    healthCheckPath: /
    envVars:
      - key: APP_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///app.db
